//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace Cmc.Engage.Models.Extn
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum msevtmgt_EventState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum msevtmgt_event_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// Container to manage and plan marketing activities that take place at a specific venue or location.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msevtmgt_event")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public partial class msevtmgt_Event : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public msevtmgt_Event() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "msevtmgt_event";
		
		public const int EntityTypeCode = 10150;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_allowanonymousregistrations")]
		public System.Nullable<bool> adx_allowanonymousregistrations
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("adx_allowanonymousregistrations");
			}
			set
			{
				this.OnPropertyChanging("adx_allowanonymousregistrations");
				this.SetAttributeValue("adx_allowanonymousregistrations", value);
				this.OnPropertyChanged("adx_allowanonymousregistrations");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("adx_portalbannerimage")]
		public Microsoft.Xrm.Sdk.EntityReference adx_portalbannerimage
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("adx_portalbannerimage");
			}
			set
			{
				this.OnPropertyChanging("adx_portalbannerimage");
				this.SetAttributeValue("adx_portalbannerimage", value);
				this.OnPropertyChanged("adx_portalbannerimage");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cmc_enddatetime")]
		public System.Nullable<System.DateTime> cmc_enddatetime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("cmc_enddatetime");
			}
			set
			{
				this.OnPropertyChanging("cmc_enddatetime");
				this.SetAttributeValue("cmc_enddatetime", value);
				this.OnPropertyChanged("cmc_enddatetime");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("cmc_startdatetime")]
		public System.Nullable<System.DateTime> cmc_startdatetime
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("cmc_startdatetime");
			}
			set
			{
				this.OnPropertyChanging("cmc_startdatetime");
				this.SetAttributeValue("cmc_startdatetime", value);
				this.OnPropertyChanged("cmc_startdatetime");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage")]
		public byte[] EntityImage
		{
			get
			{
				return this.GetAttributeValue<byte[]>("entityimage");
			}
			set
			{
				this.OnPropertyChanging("EntityImage");
				this.SetAttributeValue("entityimage", value);
				this.OnPropertyChanged("EntityImage");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_timestamp")]
		public System.Nullable<long> EntityImage_Timestamp
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("entityimage_timestamp");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_url")]
		public string EntityImage_URL
		{
			get
			{
				return this.GetAttributeValue<string>("entityimage_url");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimageid")]
		public System.Nullable<System.Guid> EntityImageId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("entityimageid");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the entity with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Determines whether an event URL is specified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyncrm_eventurlspecified")]
		public System.Nullable<bool> msdyncrm_EventURLspecified
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyncrm_eventurlspecified");
			}
		}
		
		/// <summary>
		/// The number of sessions in this event
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyncrm_sessionscount")]
		public System.Nullable<int> msdyncrm_SessionsCount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msdyncrm_sessionscount");
			}
		}
		
		/// <summary>
		/// Last Updated time of rollup field Session count.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyncrm_sessionscount_date")]
		public System.Nullable<System.DateTime> msdyncrm_SessionsCount_Date
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyncrm_sessionscount_date");
			}
		}
		
		/// <summary>
		/// State of rollup field Session count.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyncrm_sessionscount_state")]
		public System.Nullable<int> msdyncrm_SessionsCount_State
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msdyncrm_sessionscount_state");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_baserecurrenteventid")]
		public string msevtmgt_baserecurrenteventid
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_baserecurrenteventid");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_baserecurrenteventid");
				this.SetAttributeValue("msevtmgt_baserecurrenteventid", value);
				this.OnPropertyChanged("msevtmgt_baserecurrenteventid");
			}
		}
		
		/// <summary>
		/// Flight reservations booking status
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_bookedflightreservations")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_BookedFlightReservations
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_bookedflightreservations");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_BookedFlightReservations");
				this.SetAttributeValue("msevtmgt_bookedflightreservations", value);
				this.OnPropertyChanged("msevtmgt_BookedFlightReservations");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_bookrooms")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_BookRooms
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_bookrooms");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_BookRooms");
				this.SetAttributeValue("msevtmgt_bookrooms", value);
				this.OnPropertyChanged("msevtmgt_BookRooms");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_budgetallocated")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_BudgetAllocated
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_budgetallocated");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_BudgetAllocated");
				this.SetAttributeValue("msevtmgt_budgetallocated", value);
				this.OnPropertyChanged("msevtmgt_BudgetAllocated");
			}
		}
		
		/// <summary>
		/// Value of the Budget Allocated in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_budgetallocated_base")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_budgetallocated_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_budgetallocated_base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_cateringrequired")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_CateringRequired
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_cateringrequired");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_CateringRequired");
				this.SetAttributeValue("msevtmgt_cateringrequired", value);
				this.OnPropertyChanged("msevtmgt_CateringRequired");
			}
		}
		
		/// <summary>
		/// Check-in count
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_checkincount")]
		public System.Nullable<int> msevtmgt_CheckInCount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msevtmgt_checkincount");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_CheckInCount");
				this.SetAttributeValue("msevtmgt_checkincount", value);
				this.OnPropertyChanged("msevtmgt_CheckInCount");
			}
		}
		
		/// <summary>
		/// Hotel choices confirmation status
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_confirmedhotelchoices")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_ConfirmedHotelChoices
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_confirmedhotelchoices");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_ConfirmedHotelChoices");
				this.SetAttributeValue("msevtmgt_confirmedhotelchoices", value);
				this.OnPropertyChanged("msevtmgt_ConfirmedHotelChoices");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_countdownindays")]
		public System.Nullable<int> msevtmgt_CountdownInDays
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msevtmgt_countdownindays");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_createmarketingcollateral")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_CreateMarketingCollateral
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_createmarketingcollateral");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_CreateMarketingCollateral");
				this.SetAttributeValue("msevtmgt_createmarketingcollateral", value);
				this.OnPropertyChanged("msevtmgt_CreateMarketingCollateral");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_definepackagesandpricing")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_DefinePackagesandPricing
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_definepackagesandpricing");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_DefinePackagesandPricing");
				this.SetAttributeValue("msevtmgt_definepackagesandpricing", value);
				this.OnPropertyChanged("msevtmgt_DefinePackagesandPricing");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_definesessions")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_DefineSessions
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_definesessions");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_DefineSessions");
				this.SetAttributeValue("msevtmgt_definesessions", value);
				this.OnPropertyChanged("msevtmgt_DefineSessions");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_defineteam")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_DefineTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_defineteam");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_DefineTeam");
				this.SetAttributeValue("msevtmgt_defineteam", value);
				this.OnPropertyChanged("msevtmgt_DefineTeam");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_description")]
		public string msevtmgt_Description
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_description");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_Description");
				this.SetAttributeValue("msevtmgt_description", value);
				this.OnPropertyChanged("msevtmgt_Description");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_developmarketingplan")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_DevelopMarketingPlan
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_developmarketingplan");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_DevelopMarketingPlan");
				this.SetAttributeValue("msevtmgt_developmarketingplan", value);
				this.OnPropertyChanged("msevtmgt_DevelopMarketingPlan");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_earlybirdcutoffdate")]
		public System.Nullable<System.DateTime> msevtmgt_EarlyBirdCutOffDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msevtmgt_earlybirdcutoffdate");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_EarlyBirdCutOffDate");
				this.SetAttributeValue("msevtmgt_earlybirdcutoffdate", value);
				this.OnPropertyChanged("msevtmgt_EarlyBirdCutOffDate");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_eventdebriefing")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_EventDebriefing
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_eventdebriefing");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_EventDebriefing");
				this.SetAttributeValue("msevtmgt_eventdebriefing", value);
				this.OnPropertyChanged("msevtmgt_EventDebriefing");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_eventenddate")]
		public System.Nullable<System.DateTime> msevtmgt_EventEndDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msevtmgt_eventenddate");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_EventEndDate");
				this.SetAttributeValue("msevtmgt_eventenddate", value);
				this.OnPropertyChanged("msevtmgt_EventEndDate");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_eventformat")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_EventFormat
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_eventformat");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_EventFormat");
				this.SetAttributeValue("msevtmgt_eventformat", value);
				this.OnPropertyChanged("msevtmgt_EventFormat");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_eventid")]
		public System.Nullable<System.Guid> msevtmgt_EventId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("msevtmgt_eventid");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_EventId");
				this.SetAttributeValue("msevtmgt_eventid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("msevtmgt_EventId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_eventid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.msevtmgt_EventId = value;
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_eventstartdate")]
		public System.Nullable<System.DateTime> msevtmgt_EventStartDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msevtmgt_eventstartdate");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_EventStartDate");
				this.SetAttributeValue("msevtmgt_eventstartdate", value);
				this.OnPropertyChanged("msevtmgt_EventStartDate");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_eventtimezone")]
		public System.Nullable<int> msevtmgt_EventTimeZone
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msevtmgt_eventtimezone");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_EventTimeZone");
				this.SetAttributeValue("msevtmgt_eventtimezone", value);
				this.OnPropertyChanged("msevtmgt_EventTimeZone");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_eventtimezonename")]
		public string msevtmgt_EventTimeZoneName
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_eventtimezonename");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_EventTimeZoneName");
				this.SetAttributeValue("msevtmgt_eventtimezonename", value);
				this.OnPropertyChanged("msevtmgt_EventTimeZoneName");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_eventtype")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_EventType
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_eventtype");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_EventType");
				this.SetAttributeValue("msevtmgt_eventtype", value);
				this.OnPropertyChanged("msevtmgt_EventType");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_eventurl")]
		public string msevtmgt_EventURL
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_eventurl");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_EventURL");
				this.SetAttributeValue("msevtmgt_eventurl", value);
				this.OnPropertyChanged("msevtmgt_EventURL");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_eventvenuecost")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_EventVenueCost
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_eventvenuecost");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_EventVenueCost");
				this.SetAttributeValue("msevtmgt_eventvenuecost", value);
				this.OnPropertyChanged("msevtmgt_EventVenueCost");
			}
		}
		
		/// <summary>
		/// Value of the Event Venue Cost in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_eventvenuecost_base")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_eventvenuecost_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_eventvenuecost_base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_expectedoutcome")]
		public string msevtmgt_ExpectedOutcome
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_expectedoutcome");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_ExpectedOutcome");
				this.SetAttributeValue("msevtmgt_expectedoutcome", value);
				this.OnPropertyChanged("msevtmgt_ExpectedOutcome");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_followuponleads")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_FollowUpOnLeads
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_followuponleads");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_FollowUpOnLeads");
				this.SetAttributeValue("msevtmgt_followuponleads", value);
				this.OnPropertyChanged("msevtmgt_FollowUpOnLeads");
			}
		}
		
		/// <summary>
		/// Whether guest logistics are required or not.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_guestlogistics")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_GuestLogistics
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_guestlogistics");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_GuestLogistics");
				this.SetAttributeValue("msevtmgt_guestlogistics", value);
				this.OnPropertyChanged("msevtmgt_GuestLogistics");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_identifyspeakers")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_IdentifySpeakers
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_identifyspeakers");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_IdentifySpeakers");
				this.SetAttributeValue("msevtmgt_identifyspeakers", value);
				this.OnPropertyChanged("msevtmgt_IdentifySpeakers");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_identifysponsors")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_IdentifySponsors
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_identifysponsors");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_IdentifySponsors");
				this.SetAttributeValue("msevtmgt_identifysponsors", value);
				this.OnPropertyChanged("msevtmgt_IdentifySponsors");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_isrecurringevent")]
		public System.Nullable<bool> msevtmgt_IsRecurringEvent
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msevtmgt_isrecurringevent");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_IsRecurringEvent");
				this.SetAttributeValue("msevtmgt_isrecurringevent", value);
				this.OnPropertyChanged("msevtmgt_IsRecurringEvent");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_istemplate")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_istemplate
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_istemplate");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_istemplate");
				this.SetAttributeValue("msevtmgt_istemplate", value);
				this.OnPropertyChanged("msevtmgt_istemplate");
			}
		}
		
		/// <summary>
		/// The language of the webinar
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_language")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_Language
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_language");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_Language");
				this.SetAttributeValue("msevtmgt_language", value);
				this.OnPropertyChanged("msevtmgt_Language");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_makepaymentsdue")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_MakePaymentsDue
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_makepaymentsdue");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_MakePaymentsDue");
				this.SetAttributeValue("msevtmgt_makepaymentsdue", value);
				this.OnPropertyChanged("msevtmgt_MakePaymentsDue");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_manageregistrationcount")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_ManageRegistrationCount
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_manageregistrationcount");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_ManageRegistrationCount");
				this.SetAttributeValue("msevtmgt_manageregistrationcount", value);
				this.OnPropertyChanged("msevtmgt_ManageRegistrationCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_maximumeventcapacity")]
		public System.Nullable<int> msevtmgt_MaximumEventCapacity
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msevtmgt_maximumeventcapacity");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_MaximumEventCapacity");
				this.SetAttributeValue("msevtmgt_maximumeventcapacity", value);
				this.OnPropertyChanged("msevtmgt_MaximumEventCapacity");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_maxnumberofregistrations")]
		public System.Nullable<int> msevtmgt_MaxNumberOfRegistrations
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msevtmgt_maxnumberofregistrations");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_MaxNumberOfRegistrations");
				this.SetAttributeValue("msevtmgt_maxnumberofregistrations", value);
				this.OnPropertyChanged("msevtmgt_MaxNumberOfRegistrations");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_miscellaneouscosts")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_MiscellaneousCosts
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_miscellaneouscosts");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_MiscellaneousCosts");
				this.SetAttributeValue("msevtmgt_miscellaneouscosts", value);
				this.OnPropertyChanged("msevtmgt_MiscellaneousCosts");
			}
		}
		
		/// <summary>
		/// Value of the Miscellaneous Costs in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_miscellaneouscosts_base")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_miscellaneouscosts_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_miscellaneouscosts_base");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_name")]
		public string msevtmgt_Name
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_name");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_Name");
				this.SetAttributeValue("msevtmgt_name", value);
				this.OnPropertyChanged("msevtmgt_Name");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_notifyauthoritiesofevent")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_NotifyAuthoritiesOfEvent
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_notifyauthoritiesofevent");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_NotifyAuthoritiesOfEvent");
				this.SetAttributeValue("msevtmgt_notifyauthoritiesofevent", value);
				this.OnPropertyChanged("msevtmgt_NotifyAuthoritiesOfEvent");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_planregistration")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_PlanRegistration
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_planregistration");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_PlanRegistration");
				this.SetAttributeValue("msevtmgt_planregistration", value);
				this.OnPropertyChanged("msevtmgt_PlanRegistration");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_portalpaymentgateway")]
		public Microsoft.Xrm.Sdk.EntityReference msevtmgt_PortalPaymentGateway
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msevtmgt_portalpaymentgateway");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_PortalPaymentGateway");
				this.SetAttributeValue("msevtmgt_portalpaymentgateway", value);
				this.OnPropertyChanged("msevtmgt_PortalPaymentGateway");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_presentationmanagerurl")]
		public string msevtmgt_PresentationManagerUrl
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_presentationmanagerurl");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_PresentationManagerUrl");
				this.SetAttributeValue("msevtmgt_presentationmanagerurl", value);
				this.OnPropertyChanged("msevtmgt_PresentationManagerUrl");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_primarygoal")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_PrimaryGoal
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_primarygoal");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_PrimaryGoal");
				this.SetAttributeValue("msevtmgt_primarygoal", value);
				this.OnPropertyChanged("msevtmgt_PrimaryGoal");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_primaryvenue")]
		public Microsoft.Xrm.Sdk.EntityReference msevtmgt_PrimaryVenue
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msevtmgt_primaryvenue");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_PrimaryVenue");
				this.SetAttributeValue("msevtmgt_primaryvenue", value);
				this.OnPropertyChanged("msevtmgt_PrimaryVenue");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_producer")]
		public Microsoft.Xrm.Sdk.EntityReference msevtmgt_producer
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msevtmgt_producer");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_producer");
				this.SetAttributeValue("msevtmgt_producer", value);
				this.OnPropertyChanged("msevtmgt_producer");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_publiceventurl")]
		public string msevtmgt_publiceventurl
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_publiceventurl");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_publiceventurl");
				this.SetAttributeValue("msevtmgt_publiceventurl", value);
				this.OnPropertyChanged("msevtmgt_publiceventurl");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_publishstatus")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_PublishStatus
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_publishstatus");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_PublishStatus");
				this.SetAttributeValue("msevtmgt_publishstatus", value);
				this.OnPropertyChanged("msevtmgt_PublishStatus");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_readableeventid")]
		public string msevtmgt_readableeventid
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_readableeventid");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_readableeventid");
				this.SetAttributeValue("msevtmgt_readableeventid", value);
				this.OnPropertyChanged("msevtmgt_readableeventid");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_recurrencepattern")]
		public string msevtmgt_RecurrencePattern
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_recurrencepattern");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_RecurrencePattern");
				this.SetAttributeValue("msevtmgt_recurrencepattern", value);
				this.OnPropertyChanged("msevtmgt_RecurrencePattern");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_recurrenteventstatus")]
		public System.Nullable<int> msevtmgt_recurrenteventstatus
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msevtmgt_recurrenteventstatus");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_recurrenteventstatus");
				this.SetAttributeValue("msevtmgt_recurrenteventstatus", value);
				this.OnPropertyChanged("msevtmgt_recurrenteventstatus");
			}
		}
		
		/// <summary>
		/// Registration count of the Event.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_registrationcount")]
		public System.Nullable<int> msevtmgt_RegistrationCount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msevtmgt_registrationcount");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_RegistrationCount");
				this.SetAttributeValue("msevtmgt_registrationcount", value);
				this.OnPropertyChanged("msevtmgt_RegistrationCount");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_registrationstarget")]
		public System.Nullable<int> msevtmgt_RegistrationsTarget
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msevtmgt_registrationstarget");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_RegistrationsTarget");
				this.SetAttributeValue("msevtmgt_registrationstarget", value);
				this.OnPropertyChanged("msevtmgt_RegistrationsTarget");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_requestsponsorship")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_RequestSponsorship
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_requestsponsorship");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_RequestSponsorship");
				this.SetAttributeValue("msevtmgt_requestsponsorship", value);
				this.OnPropertyChanged("msevtmgt_RequestSponsorship");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_revenuefromsponsorship")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_RevenueFromSponsorship
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_revenuefromsponsorship");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_RevenueFromSponsorship");
				this.SetAttributeValue("msevtmgt_revenuefromsponsorship", value);
				this.OnPropertyChanged("msevtmgt_RevenueFromSponsorship");
			}
		}
		
		/// <summary>
		/// Value of the Revenue from Sponsorship in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_revenuefromsponsorship_base")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_revenuefromsponsorship_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_revenuefromsponsorship_base");
			}
		}
		
		/// <summary>
		/// Airport pickups scheduling status
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_scheduleairportpickups")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_ScheduleAirportPickups
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_scheduleairportpickups");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_ScheduleAirportPickups");
				this.SetAttributeValue("msevtmgt_scheduleairportpickups", value);
				this.OnPropertyChanged("msevtmgt_ScheduleAirportPickups");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_schedulesessions")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_ScheduleSessions
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_schedulesessions");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_ScheduleSessions");
				this.SetAttributeValue("msevtmgt_schedulesessions", value);
				this.OnPropertyChanged("msevtmgt_ScheduleSessions");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_selectspeakers")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_SelectSpeakers
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_selectspeakers");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_SelectSpeakers");
				this.SetAttributeValue("msevtmgt_selectspeakers", value);
				this.OnPropertyChanged("msevtmgt_SelectSpeakers");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_selectvendors")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_SelectVendors
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_selectvendors");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_SelectVendors");
				this.SetAttributeValue("msevtmgt_selectvendors", value);
				this.OnPropertyChanged("msevtmgt_SelectVendors");
			}
		}
		
		/// <summary>
		/// Event invitation sending status
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_sendeventinvitation")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_SendEventInvitation
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_sendeventinvitation");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_SendEventInvitation");
				this.SetAttributeValue("msevtmgt_sendeventinvitation", value);
				this.OnPropertyChanged("msevtmgt_SendEventInvitation");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_sendmarketingmaterial")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_SendMarketingMaterial
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_sendmarketingmaterial");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_SendMarketingMaterial");
				this.SetAttributeValue("msevtmgt_sendmarketingmaterial", value);
				this.OnPropertyChanged("msevtmgt_SendMarketingMaterial");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_sendpreeventreminders")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_SendPreEventReminders
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_sendpreeventreminders");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_SendPreEventReminders");
				this.SetAttributeValue("msevtmgt_sendpreeventreminders", value);
				this.OnPropertyChanged("msevtmgt_SendPreEventReminders");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_sendsurveys")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_SendSurveys
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_sendsurveys");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_SendSurveys");
				this.SetAttributeValue("msevtmgt_sendsurveys", value);
				this.OnPropertyChanged("msevtmgt_SendSurveys");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_sendthankyouemails")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_SendThankYouEmails
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_sendthankyouemails");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_SendThankYouEmails");
				this.SetAttributeValue("msevtmgt_sendthankyouemails", value);
				this.OnPropertyChanged("msevtmgt_SendThankYouEmails");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_showwaitlist")]
		public System.Nullable<bool> msevtmgt_showwaitlist
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msevtmgt_showwaitlist");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_showwaitlist");
				this.SetAttributeValue("msevtmgt_showwaitlist", value);
				this.OnPropertyChanged("msevtmgt_showwaitlist");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_targetrevenue")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_TargetRevenue
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_targetrevenue");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_TargetRevenue");
				this.SetAttributeValue("msevtmgt_targetrevenue", value);
				this.OnPropertyChanged("msevtmgt_TargetRevenue");
			}
		}
		
		/// <summary>
		/// Value of the Target Revenue in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_targetrevenue_base")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_targetrevenue_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_targetrevenue_base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_teamdebriefing")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_TeamDebriefing
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_teamdebriefing");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_TeamDebriefing");
				this.SetAttributeValue("msevtmgt_teamdebriefing", value);
				this.OnPropertyChanged("msevtmgt_TeamDebriefing");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_totalcostofeventsactivities")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_TotalCostOfEventsActivities
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_totalcostofeventsactivities");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_TotalCostOfEventsActivities");
				this.SetAttributeValue("msevtmgt_totalcostofeventsactivities", value);
				this.OnPropertyChanged("msevtmgt_TotalCostOfEventsActivities");
			}
		}
		
		/// <summary>
		/// Value of the Total Cost of Events Activities in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_totalcostofeventsactivities_base")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_totalcostofeventsactivities_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_totalcostofeventsactivities_base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_totalcostofexternalmembers")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_TotalCostOfExternalMembers
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_totalcostofexternalmembers");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_TotalCostOfExternalMembers");
				this.SetAttributeValue("msevtmgt_totalcostofexternalmembers", value);
				this.OnPropertyChanged("msevtmgt_TotalCostOfExternalMembers");
			}
		}
		
		/// <summary>
		/// Value of the Total cost of External Members in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_totalcostofexternalmembers_base")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_totalcostofexternalmembers_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_totalcostofexternalmembers_base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_totalregistrationfee")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_TotalRegistrationFee
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_totalregistrationfee");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_TotalRegistrationFee");
				this.SetAttributeValue("msevtmgt_totalregistrationfee", value);
				this.OnPropertyChanged("msevtmgt_TotalRegistrationFee");
			}
		}
		
		/// <summary>
		/// Value of the Total Registration Fee in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_totalregistrationfee_base")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_totalregistrationfee_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_totalregistrationfee_base");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_totalrevenuefromtheevent")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_TotalRevenueFromTheEvent
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_totalrevenuefromtheevent");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_TotalRevenueFromTheEvent");
				this.SetAttributeValue("msevtmgt_totalrevenuefromtheevent", value);
				this.OnPropertyChanged("msevtmgt_TotalRevenueFromTheEvent");
			}
		}
		
		/// <summary>
		/// Value of the Total Revenue from the event in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_totalrevenuefromtheevent_base")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_totalrevenuefromtheevent_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_totalrevenuefromtheevent_base");
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference msevtmgt_TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msevtmgt_transactioncurrencyid");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_TransactionCurrencyId");
				this.SetAttributeValue("msevtmgt_transactioncurrencyid", value);
				this.OnPropertyChanged("msevtmgt_TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// Waitlist Starting Point
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_waitliststartingpoint")]
		public System.Nullable<int> msevtmgt_WaitlistStartingPoint
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msevtmgt_waitliststartingpoint");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_WaitlistStartingPoint");
				this.SetAttributeValue("msevtmgt_waitliststartingpoint", value);
				this.OnPropertyChanged("msevtmgt_WaitlistStartingPoint");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_waitlistthisevent")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_WaitlistthisEvent
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_waitlistthisevent");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_WaitlistthisEvent");
				this.SetAttributeValue("msevtmgt_waitlistthisevent", value);
				this.OnPropertyChanged("msevtmgt_WaitlistthisEvent");
			}
		}
		
		/// <summary>
		/// Webinar Configuration
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_webinarconfigurationid")]
		public Microsoft.Xrm.Sdk.EntityReference msevtmgt_WebinarConfigurationId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msevtmgt_webinarconfigurationid");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_WebinarConfigurationId");
				this.SetAttributeValue("msevtmgt_webinarconfigurationid", value);
				this.OnPropertyChanged("msevtmgt_WebinarConfigurationId");
			}
		}
		
		/// <summary>
		/// Webinar ID of the Event.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_webinarid")]
		public string msevtmgt_WebinarID
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_webinarid");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_WebinarID");
				this.SetAttributeValue("msevtmgt_webinarid", value);
				this.OnPropertyChanged("msevtmgt_WebinarID");
			}
		}
		
		/// <summary>
		/// Whether the webinar creation notification has been seen or not
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_webinarnotificationseen")]
		public System.Nullable<bool> msevtmgt_webinarnotificationseen
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msevtmgt_webinarnotificationseen");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_webinarnotificationseen");
				this.SetAttributeValue("msevtmgt_webinarnotificationseen", value);
				this.OnPropertyChanged("msevtmgt_webinarnotificationseen");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_webinaroperation")]
		public string msevtmgt_webinaroperation
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_webinaroperation");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_webinaroperation");
				this.SetAttributeValue("msevtmgt_webinaroperation", value);
				this.OnPropertyChanged("msevtmgt_webinaroperation");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_webinarstatus")]
		public string msevtmgt_webinarstatus
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_webinarstatus");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_webinarstatus");
				this.SetAttributeValue("msevtmgt_webinarstatus", value);
				this.OnPropertyChanged("msevtmgt_webinarstatus");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_webinarstatusreason")]
		public string msevtmgt_webinarstatusreason
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_webinarstatusreason");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_webinarstatusreason");
				this.SetAttributeValue("msevtmgt_webinarstatusreason", value);
				this.OnPropertyChanged("msevtmgt_webinarstatusreason");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_webinartype")]
		public Microsoft.Xrm.Sdk.EntityReference msevtmgt_WebinarType
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msevtmgt_webinartype");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_WebinarType");
				this.SetAttributeValue("msevtmgt_webinartype", value);
				this.OnPropertyChanged("msevtmgt_WebinarType");
			}
		}
		
		/// <summary>
		/// URL of the webinar. This might be URL of external webinar provider.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_webinarurl")]
		public string msevtmgt_webinarURL
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_webinarurl");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_webinarURL");
				this.SetAttributeValue("msevtmgt_webinarurl", value);
				this.OnPropertyChanged("msevtmgt_webinarURL");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner ID
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Contains the id of the process associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		public System.Nullable<System.Guid> processid
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
			}
			set
			{
				this.OnPropertyChanging("processid");
				this.SetAttributeValue("processid", value);
				this.OnPropertyChanged("processid");
			}
		}
		
		/// <summary>
		/// Contains the id of the stage where the entity is located.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		public System.Nullable<System.Guid> stageid
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
			}
			set
			{
				this.OnPropertyChanging("stageid");
				this.SetAttributeValue("stageid", value);
				this.OnPropertyChanged("stageid");
			}
		}
		
		/// <summary>
		/// Status of the Event
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<Cmc.Engage.Models.Extn.msevtmgt_EventState> statecode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((Cmc.Engage.Models.Extn.msevtmgt_EventState)(System.Enum.ToObject(typeof(Cmc.Engage.Models.Extn.msevtmgt_EventState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("statecode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Event
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public System.Nullable<Cmc.Engage.Models.Extn.msevtmgt_event_statuscode> statuscode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
				if ((optionSet != null))
				{
					return ((Cmc.Engage.Models.Extn.msevtmgt_event_statuscode)(System.Enum.ToObject(typeof(Cmc.Engage.Models.Extn.msevtmgt_event_statuscode), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				if ((value == null))
				{
					this.SetAttributeValue("statuscode", null);
				}
				else
				{
					this.SetAttributeValue("statuscode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// A comma separated list of string values representing the unique identifiers of stages in a Business Process Flow Instance in the order that they occur.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
		public string traversedpath
		{
			get
			{
				return this.GetAttributeValue<string>("traversedpath");
			}
			set
			{
				this.OnPropertyChanging("traversedpath");
				this.SetAttributeValue("traversedpath", value);
				this.OnPropertyChanged("traversedpath");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// N:1 msevtmgt_venue_msevtmgt_event_PrimaryVenue
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_primaryvenue")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msevtmgt_venue_msevtmgt_event_PrimaryVenue")]
		public Cmc.Engage.Models.Extn.msevtmgt_Venue msevtmgt_venue_msevtmgt_event_PrimaryVenue
		{
			get
			{
				return this.GetRelatedEntity<Cmc.Engage.Models.Extn.msevtmgt_Venue>("msevtmgt_venue_msevtmgt_event_PrimaryVenue", null);
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_venue_msevtmgt_event_PrimaryVenue");
				this.SetRelatedEntity<Cmc.Engage.Models.Extn.msevtmgt_Venue>("msevtmgt_venue_msevtmgt_event_PrimaryVenue", null, value);
				this.OnPropertyChanged("msevtmgt_venue_msevtmgt_event_PrimaryVenue");
			}
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum msevtmgt_VenueState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public enum msevtmgt_venue_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	/// <summary>
	/// The Venue describes the location at which all event sessions and activities take place. A single event venue can be comprised of zero or more buildings, each of which can have zero or more rooms where sessions take place.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msevtmgt_venue")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public partial class msevtmgt_Venue : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public msevtmgt_Venue() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "msevtmgt_venue";
		
		public const int EntityTypeCode = 10177;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the entity with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// There are accessible toilets or not.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_accessibletoilets")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_AccessibleToilets
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_accessibletoilets");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_AccessibleToilets");
				this.SetAttributeValue("msevtmgt_accessibletoilets", value);
				this.OnPropertyChanged("msevtmgt_AccessibleToilets");
			}
		}
		
		/// <summary>
		/// Some additional facilities which is not covered by available options.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_additionalfacilities")]
		public string msevtmgt_AdditionalFacilities
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_additionalfacilities");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_AdditionalFacilities");
				this.SetAttributeValue("msevtmgt_additionalfacilities", value);
				this.OnPropertyChanged("msevtmgt_AdditionalFacilities");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_addresscomposite")]
		public string msevtmgt_AddressComposite
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_addresscomposite");
			}
		}
		
		/// <summary>
		/// Address (except of city, country/region, state or province and postal code).
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_addressline1")]
		public string msevtmgt_AddressLine1
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_addressline1");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_AddressLine1");
				this.SetAttributeValue("msevtmgt_addressline1", value);
				this.OnPropertyChanged("msevtmgt_AddressLine1");
			}
		}
		
		/// <summary>
		/// Additional address details.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_addressline2")]
		public string msevtmgt_AddressLine2
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_addressline2");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_AddressLine2");
				this.SetAttributeValue("msevtmgt_addressline2", value);
				this.OnPropertyChanged("msevtmgt_AddressLine2");
			}
		}
		
		/// <summary>
		/// Additional address details.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_addressline3")]
		public string msevtmgt_AddressLine3
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_addressline3");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_AddressLine3");
				this.SetAttributeValue("msevtmgt_addressline3", value);
				this.OnPropertyChanged("msevtmgt_AddressLine3");
			}
		}
		
		/// <summary>
		/// Unique identifier for Building associated with Venue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_buildingid")]
		public Microsoft.Xrm.Sdk.EntityReference msevtmgt_BuildingId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msevtmgt_buildingid");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_BuildingId");
				this.SetAttributeValue("msevtmgt_buildingid", value);
				this.OnPropertyChanged("msevtmgt_BuildingId");
			}
		}
		
		/// <summary>
		/// City part of address info.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_city")]
		public string msevtmgt_City
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_city");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_City");
				this.SetAttributeValue("msevtmgt_city", value);
				this.OnPropertyChanged("msevtmgt_City");
			}
		}
		
		/// <summary>
		/// Cost of the venue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_cost")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_Cost
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_cost");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_Cost");
				this.SetAttributeValue("msevtmgt_cost", value);
				this.OnPropertyChanged("msevtmgt_Cost");
			}
		}
		
		/// <summary>
		/// Value of the Cost in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_cost_base")]
		public Microsoft.Xrm.Sdk.Money msevtmgt_cost_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msevtmgt_cost_base");
			}
		}
		
		/// <summary>
		/// Country/Region part of address info.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_country")]
		public string msevtmgt_Country
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_country");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_Country");
				this.SetAttributeValue("msevtmgt_country", value);
				this.OnPropertyChanged("msevtmgt_Country");
			}
		}
		
		/// <summary>
		/// Description of the venue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_description")]
		public string msevtmgt_Description
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_description");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_Description");
				this.SetAttributeValue("msevtmgt_description", value);
				this.OnPropertyChanged("msevtmgt_Description");
			}
		}
		
		/// <summary>
		/// There is disabled access or not.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_disabledaccess")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_DisabledAccess
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_disabledaccess");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_DisabledAccess");
				this.SetAttributeValue("msevtmgt_disabledaccess", value);
				this.OnPropertyChanged("msevtmgt_DisabledAccess");
			}
		}
		
		/// <summary>
		/// There is disabled parking or not.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_disabledparking")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_DisabledParking
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_disabledparking");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_DisabledParking");
				this.SetAttributeValue("msevtmgt_disabledparking", value);
				this.OnPropertyChanged("msevtmgt_DisabledParking");
			}
		}
		
		/// <summary>
		/// Email. Part of the venue contact information.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_email")]
		public string msevtmgt_Email
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_email");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_Email");
				this.SetAttributeValue("msevtmgt_email", value);
				this.OnPropertyChanged("msevtmgt_Email");
			}
		}
		
		/// <summary>
		/// Estimated capacity of the venue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_estcapacity")]
		public System.Nullable<int> msevtmgt_EstCapacity
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msevtmgt_estcapacity");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_EstCapacity");
				this.SetAttributeValue("msevtmgt_estcapacity", value);
				this.OnPropertyChanged("msevtmgt_EstCapacity");
			}
		}
		
		/// <summary>
		/// The name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_name")]
		public string msevtmgt_Name
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_name");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_Name");
				this.SetAttributeValue("msevtmgt_name", value);
				this.OnPropertyChanged("msevtmgt_Name");
			}
		}
		
		/// <summary>
		/// Unique identifier for Venue associated with Venue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_parentvenueid")]
		public Microsoft.Xrm.Sdk.EntityReference msevtmgt_ParentVenueId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msevtmgt_parentvenueid");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_ParentVenueId");
				this.SetAttributeValue("msevtmgt_parentvenueid", value);
				this.OnPropertyChanged("msevtmgt_ParentVenueId");
			}
		}
		
		/// <summary>
		/// Postal code part of address info.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_postalcode")]
		public string msevtmgt_PostalCode
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_postalcode");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_PostalCode");
				this.SetAttributeValue("msevtmgt_postalcode", value);
				this.OnPropertyChanged("msevtmgt_PostalCode");
			}
		}
		
		/// <summary>
		/// A person who is responsible for the venue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_primarycontact")]
		public Microsoft.Xrm.Sdk.EntityReference msevtmgt_PrimaryContact
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msevtmgt_primarycontact");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_PrimaryContact");
				this.SetAttributeValue("msevtmgt_primarycontact", value);
				this.OnPropertyChanged("msevtmgt_PrimaryContact");
			}
		}
		
		/// <summary>
		/// There is available public telephone or not.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_publictelephoneavailable")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_PublicTelephoneAvailable
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_publictelephoneavailable");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_PublicTelephoneAvailable");
				this.SetAttributeValue("msevtmgt_publictelephoneavailable", value);
				this.OnPropertyChanged("msevtmgt_PublicTelephoneAvailable");
			}
		}
		
		/// <summary>
		/// Unique identifier for Room associated with Venue.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_roomid")]
		public Microsoft.Xrm.Sdk.EntityReference msevtmgt_RoomId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msevtmgt_roomid");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_RoomId");
				this.SetAttributeValue("msevtmgt_roomid", value);
				this.OnPropertyChanged("msevtmgt_RoomId");
			}
		}
		
		/// <summary>
		/// State or province part of address info.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_stateprovince")]
		public string msevtmgt_StateProvince
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_stateprovince");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_StateProvince");
				this.SetAttributeValue("msevtmgt_stateprovince", value);
				this.OnPropertyChanged("msevtmgt_StateProvince");
			}
		}
		
		/// <summary>
		/// Telephone 1. Part of the venue contact information.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_telephone1")]
		public string msevtmgt_Telephone1
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_telephone1");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_Telephone1");
				this.SetAttributeValue("msevtmgt_telephone1", value);
				this.OnPropertyChanged("msevtmgt_Telephone1");
			}
		}
		
		/// <summary>
		/// Telephone 2. Part of the venue contact information.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_telephone2")]
		public string msevtmgt_Telephone2
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_telephone2");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_Telephone2");
				this.SetAttributeValue("msevtmgt_telephone2", value);
				this.OnPropertyChanged("msevtmgt_Telephone2");
			}
		}
		
		/// <summary>
		/// Telephone 3. Part of the venue contact information.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_telephone3")]
		public string msevtmgt_Telephone3
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_telephone3");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_Telephone3");
				this.SetAttributeValue("msevtmgt_telephone3", value);
				this.OnPropertyChanged("msevtmgt_Telephone3");
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference msevtmgt_TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msevtmgt_transactioncurrencyid");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_TransactionCurrencyId");
				this.SetAttributeValue("msevtmgt_transactioncurrencyid", value);
				this.OnPropertyChanged("msevtmgt_TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_venueid")]
		public System.Nullable<System.Guid> msevtmgt_VenueId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("msevtmgt_venueid");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_VenueId");
				this.SetAttributeValue("msevtmgt_venueid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("msevtmgt_VenueId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_venueid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.msevtmgt_VenueId = value;
			}
		}
		
		/// <summary>
		/// Website. Part of the venue contact information.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_website")]
		public string msevtmgt_Website
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_website");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_Website");
				this.SetAttributeValue("msevtmgt_website", value);
				this.OnPropertyChanged("msevtmgt_Website");
			}
		}
		
		/// <summary>
		/// There is available wifi or not.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_wifiavailable")]
		public Microsoft.Xrm.Sdk.OptionSetValue msevtmgt_WifiAvailable
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("msevtmgt_wifiavailable");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_WifiAvailable");
				this.SetAttributeValue("msevtmgt_wifiavailable", value);
				this.OnPropertyChanged("msevtmgt_WifiAvailable");
			}
		}
		
		/// <summary>
		/// Wifi password.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_wifipassword")]
		public string msevtmgt_WifiPassword
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_wifipassword");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_WifiPassword");
				this.SetAttributeValue("msevtmgt_wifipassword", value);
				this.OnPropertyChanged("msevtmgt_WifiPassword");
			}
		}
		
		/// <summary>
		/// SSID of Wifi
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_wifissid")]
		public string msevtmgt_WifiSSID
		{
			get
			{
				return this.GetAttributeValue<string>("msevtmgt_wifissid");
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_WifiSSID");
				this.SetAttributeValue("msevtmgt_wifissid", value);
				this.OnPropertyChanged("msevtmgt_WifiSSID");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Venue
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<Cmc.Engage.Models.Extn.msevtmgt_VenueState> statecode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((Cmc.Engage.Models.Extn.msevtmgt_VenueState)(System.Enum.ToObject(typeof(Cmc.Engage.Models.Extn.msevtmgt_VenueState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("statecode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Venue
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public System.Nullable<Cmc.Engage.Models.Extn.msevtmgt_venue_statuscode> statuscode
		{
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
				if ((optionSet != null))
				{
					return ((Cmc.Engage.Models.Extn.msevtmgt_venue_statuscode)(System.Enum.ToObject(typeof(Cmc.Engage.Models.Extn.msevtmgt_venue_statuscode), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				if ((value == null))
				{
					this.SetAttributeValue("statuscode", null);
				}
				else
				{
					this.SetAttributeValue("statuscode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N msevtmgt_msevtmgt_venue_msevtmgt_venue
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msevtmgt_msevtmgt_venue_msevtmgt_venue", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<Cmc.Engage.Models.Extn.msevtmgt_Venue> Referencedmsevtmgt_msevtmgt_venue_msevtmgt_venue
		{
			get
			{
				return this.GetRelatedEntities<Cmc.Engage.Models.Extn.msevtmgt_Venue>("msevtmgt_msevtmgt_venue_msevtmgt_venue", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			set
			{
				this.OnPropertyChanging("Referencedmsevtmgt_msevtmgt_venue_msevtmgt_venue");
				this.SetRelatedEntities<Cmc.Engage.Models.Extn.msevtmgt_Venue>("msevtmgt_msevtmgt_venue_msevtmgt_venue", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referencedmsevtmgt_msevtmgt_venue_msevtmgt_venue");
			}
		}
		
		/// <summary>
		/// 1:N msevtmgt_venue_msevtmgt_event_PrimaryVenue
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msevtmgt_venue_msevtmgt_event_PrimaryVenue")]
		public System.Collections.Generic.IEnumerable<Cmc.Engage.Models.Extn.msevtmgt_Event> msevtmgt_venue_msevtmgt_event_PrimaryVenue
		{
			get
			{
				return this.GetRelatedEntities<Cmc.Engage.Models.Extn.msevtmgt_Event>("msevtmgt_venue_msevtmgt_event_PrimaryVenue", null);
			}
			set
			{
				this.OnPropertyChanging("msevtmgt_venue_msevtmgt_event_PrimaryVenue");
				this.SetRelatedEntities<Cmc.Engage.Models.Extn.msevtmgt_Event>("msevtmgt_venue_msevtmgt_event_PrimaryVenue", null, value);
				this.OnPropertyChanged("msevtmgt_venue_msevtmgt_event_PrimaryVenue");
			}
		}
		
		/// <summary>
		/// N:1 msevtmgt_msevtmgt_venue_msevtmgt_venue
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msevtmgt_parentvenueid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msevtmgt_msevtmgt_venue_msevtmgt_venue", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public Cmc.Engage.Models.Extn.msevtmgt_Venue Referencingmsevtmgt_msevtmgt_venue_msevtmgt_venue
		{
			get
			{
				return this.GetRelatedEntity<Cmc.Engage.Models.Extn.msevtmgt_Venue>("msevtmgt_msevtmgt_venue_msevtmgt_venue", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			set
			{
				this.OnPropertyChanging("Referencingmsevtmgt_msevtmgt_venue_msevtmgt_venue");
				this.SetRelatedEntity<Cmc.Engage.Models.Extn.msevtmgt_Venue>("msevtmgt_msevtmgt_venue_msevtmgt_venue", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingmsevtmgt_msevtmgt_venue_msevtmgt_venue");
			}
		}
	}
	
	/// <summary>
	/// Represents a source of entities bound to a CRM service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "9.0.0.9154")]
	public partial class ModelContext : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public ModelContext(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Cmc.Engage.Models.Extn.msevtmgt_Event"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Cmc.Engage.Models.Extn.msevtmgt_Event> msevtmgt_EventSet
		{
			get
			{
				return this.CreateQuery<Cmc.Engage.Models.Extn.msevtmgt_Event>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="Cmc.Engage.Models.Extn.msevtmgt_Venue"/> entities.
		/// </summary>
		public System.Linq.IQueryable<Cmc.Engage.Models.Extn.msevtmgt_Venue> msevtmgt_VenueSet
		{
			get
			{
				return this.CreateQuery<Cmc.Engage.Models.Extn.msevtmgt_Venue>();
			}
		}
	}
}
