//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cmc.Engage.WebResources.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ResourceStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Cmc.Engage.WebResources.Resources.ResourceStrings", typeof(ResourceStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred accepting one or more of the selected Appointments. Please try again..
        /// </summary>
        internal static string AcceptAppointment_MultipleErrors {
            get {
                return ResourceManager.GetString("AcceptAppointment_MultipleErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred accepting the selected Appointment. Please try again..
        /// </summary>
        internal static string AcceptAppointment_SingleError {
            get {
                return ResourceManager.GetString("AcceptAppointment_SingleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully accepted all Appointments.
        /// </summary>
        internal static string AcceptAppointment_Success {
            get {
                return ResourceManager.GetString("AcceptAppointment_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate Student Group.
        /// </summary>
        internal static string ActivateStudentGroupTitle {
            get {
                return ResourceManager.GetString("ActivateStudentGroupTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        internal static string ActiveButton {
            get {
                return ResourceManager.GetString("ActiveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change the expiry date to activate groups in which the date occurred in the past..
        /// </summary>
        internal static string ActiveGroups {
            get {
                return ResourceManager.GetString("ActiveGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Option.
        /// </summary>
        internal static string AddOption {
            get {
                return ResourceManager.GetString("AddOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Question.
        /// </summary>
        internal static string AddQuestion {
            get {
                return ResourceManager.GetString("AddQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advisor.
        /// </summary>
        internal static string Advisor {
            get {
                return ResourceManager.GetString("Advisor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Connections.
        /// </summary>
        internal static string AllConnection {
            get {
                return ResourceManager.GetString("AllConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appointment.
        /// </summary>
        internal static string AppointmentButton {
            get {
                return ResourceManager.GetString("AppointmentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign.
        /// </summary>
        internal static string AssignButton {
            get {
                return ResourceManager.GetString("AssignButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned to Staff.
        /// </summary>
        internal static string AssignedStaff {
            get {
                return ResourceManager.GetString("AssignedStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Campus Survey.
        /// </summary>
        internal static string AssignStaffSurveyTitle {
            get {
                return ResourceManager.GetString("AssignStaffSurveyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success plans are not assigned as an Academic Period record is not associated with the following students:.
        /// </summary>
        internal static string AssignSuccessPlanDialog_FailureMessageForNoAcademicPeriod {
            get {
                return ResourceManager.GetString("AssignSuccessPlanDialog_FailureMessageForNoAcademicPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} Success plans are not assigned as an Academic Period record is not associated with the following students: Their names are:.
        /// </summary>
        internal static string AssignSuccessPlanDialog_FailureMessageForNoAcademicPeriodFullText {
            get {
                return ResourceManager.GetString("AssignSuccessPlanDialog_FailureMessageForNoAcademicPeriodFullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Plan already exists for this Student therefore not re-assigned..
        /// </summary>
        internal static string AssignSuccessPlanDialog_FailureMessageForSingleStudent {
            get {
                return ResourceManager.GetString("AssignSuccessPlanDialog_FailureMessageForSingleStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not determine the Students to assign Success Plans to. This page will not function correctly..
        /// </summary>
        internal static string AssignSuccessPlanDialog_NoStudentsMessage {
            get {
                return ResourceManager.GetString("AssignSuccessPlanDialog_NoStudentsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Success Plan Template.
        /// </summary>
        internal static string AssignSuccessPlanDialog_SelectSuccessPlanTemplateMessage {
            get {
                return ResourceManager.GetString("AssignSuccessPlanDialog_SelectSuccessPlanTemplateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Plan already exists for selected Students therefore not re-assigned..
        /// </summary>
        internal static string AssignSuccessPlanDialog_SuccessMessageForAllDuplicates {
            get {
                return ResourceManager.GetString("AssignSuccessPlanDialog_SuccessMessageForAllDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Plans have been assigned for all selected Students..
        /// </summary>
        internal static string AssignSuccessPlanDialog_SuccessMessageForNoDuplicates {
            get {
                return ResourceManager.GetString("AssignSuccessPlanDialog_SuccessMessageForNoDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Success Plan has been assigned to this Student..
        /// </summary>
        internal static string AssignSuccessPlanDialog_SuccessMessageForSingleStudent {
            get {
                return ResourceManager.GetString("AssignSuccessPlanDialog_SuccessMessageForSingleStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected Students were skipped since they already had the Success Plan assigned..
        /// </summary>
        internal static string AssignSuccessPlanDialog_SuccessMessageForSomeDuplicates {
            get {
                return ResourceManager.GetString("AssignSuccessPlanDialog_SuccessMessageForSomeDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} of {1} selected Students were skipped since they already had the Success Plan assigned.Their names are : .
        /// </summary>
        internal static string AssignSuccessPlanDuplicateMessage {
            get {
                return ResourceManager.GetString("AssignSuccessPlanDuplicateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Success Plan.
        /// </summary>
        internal static string AssignSuccessPlanTitle {
            get {
                return ResourceManager.GetString("AssignSuccessPlanTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendees.
        /// </summary>
        internal static string Attendees {
            get {
                return ResourceManager.GetString("Attendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute.
        /// </summary>
        internal static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attribute or Relationship of.
        /// </summary>
        internal static string AttributePicker_Label {
            get {
                return ResourceManager.GetString("AttributePicker_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must provide a value for Attribute..
        /// </summary>
        internal static string AttributeSelector_NoAttributeWarning {
            get {
                return ResourceManager.GetString("AttributeSelector_NoAttributeWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DOM Definition Execution Order Attribute Selector.
        /// </summary>
        internal static string AttributeTitle {
            get {
                return ResourceManager.GetString("AttributeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete this question.
        /// </summary>
        internal static string CannotDeleteQuestionText {
            get {
                return ResourceManager.GetString("CannotDeleteQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        internal static string ChatButton {
            get {
                return ResourceManager.GetString("ChatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse Question.
        /// </summary>
        internal static string CollapseQuestion {
            get {
                return ResourceManager.GetString("CollapseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed Date.
        /// </summary>
        internal static string CompletedDate {
            get {
                return ResourceManager.GetString("CompletedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation Dialog.
        /// </summary>
        internal static string ConfirmationDialog {
            get {
                return ResourceManager.GetString("ConfirmationDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred declining one or more of the selected Appointments. Please try again..
        /// </summary>
        internal static string DeclineAppointment_MultipleErrors {
            get {
                return ResourceManager.GetString("DeclineAppointment_MultipleErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred declining the selected Appointment. Please try again..
        /// </summary>
        internal static string DeclineAppointment_SingleError {
            get {
                return ResourceManager.GetString("DeclineAppointment_SingleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully declined all Appointments.
        /// </summary>
        internal static string DeclineAppointment_Success {
            get {
                return ResourceManager.GetString("DeclineAppointment_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple DOM Definition Logic records missing..
        /// </summary>
        internal static string DefinitionLogicAttributeMismatch_MultipleErrors {
            get {
                return ResourceManager.GetString("DefinitionLogicAttributeMismatch_MultipleErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a DOM Definition Logic missing for {0}..
        /// </summary>
        internal static string DefinitionLogicAttributeMismatch_SingleError {
            get {
                return ResourceManager.GetString("DefinitionLogicAttributeMismatch_SingleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty or Non-Present fields present in degree planning URL: .
        /// </summary>
        internal static string DegreePlanningURL_EmptyFields {
            get {
                return ResourceManager.GetString("DegreePlanningURL_EmptyFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to generate degree planning URL, contact field(s) in the form have been modified..
        /// </summary>
        internal static string DegreePlanningURL_Error {
            get {
                return ResourceManager.GetString("DegreePlanningURL_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree planning URL undefined..
        /// </summary>
        internal static string DegreePlanningURL_Undefined {
            get {
                return ResourceManager.GetString("DegreePlanningURL_Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Option.
        /// </summary>
        internal static string DeleteOption {
            get {
                return ResourceManager.GetString("DeleteOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Question.
        /// </summary>
        internal static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete this question?.
        /// </summary>
        internal static string DeleteQuestionConfirmation {
            get {
                return ResourceManager.GetString("DeleteQuestionConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Department.
        /// </summary>
        internal static string Department {
            get {
                return ResourceManager.GetString("Department", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are multiple DOM Definition Execution Order records missing..
        /// </summary>
        internal static string DomExecutionOrderAttributeMismatch_MultipleErrors {
            get {
                return ResourceManager.GetString("DomExecutionOrderAttributeMismatch_MultipleErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a DOM Definition Execution Order missing for {0}..
        /// </summary>
        internal static string DomExecutionOrderAttributeMismatch_SingleError {
            get {
                return ResourceManager.GetString("DomExecutionOrderAttributeMismatch_SingleError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Due Date.
        /// </summary>
        internal static string DueDate {
            get {
                return ResourceManager.GetString("DueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        internal static string Duration {
            get {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email sent successfully.
        /// </summary>
        internal static string Email_Success {
            get {
                return ResourceManager.GetString("Email_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string EmailButton {
            get {
                return ResourceManager.GetString("EmailButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The questions cannot be blank.
        /// </summary>
        internal static string EmptyQuestionText {
            get {
                return ResourceManager.GetString("EmptyQuestionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        internal static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an option.
        /// </summary>
        internal static string EnterOption {
            get {
                return ResourceManager.GetString("EnterOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a question.
        /// </summary>
        internal static string EnterQuestion {
            get {
                return ResourceManager.GetString("EnterQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected entity cannot be changed after creating the record..
        /// </summary>
        internal static string EntityPicker_DisableAlert {
            get {
                return ResourceManager.GetString("EntityPicker_DisableAlert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Entity.
        /// </summary>
        internal static string EntityPicker_Label {
            get {
                return ResourceManager.GetString("EntityPicker_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error matching configuration..
        /// </summary>
        internal static string Error_matching_configuration {
            get {
                return ResourceManager.GetString("Error_matching_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred : .
        /// </summary>
        internal static string ErrorPrefix {
            get {
                return ResourceManager.GetString("ErrorPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event.
        /// </summary>
        internal static string EventButton {
            get {
                return ResourceManager.GetString("EventButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand Question.
        /// </summary>
        internal static string ExpandQuestion {
            get {
                return ResourceManager.GetString("ExpandQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expire Date.
        /// </summary>
        internal static string ExpireDate {
            get {
                return ResourceManager.GetString("ExpireDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string FromString {
            get {
                return ResourceManager.GetString("FromString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred.Contact your administrator..
        /// </summary>
        internal static string Generic_ContactAdminError {
            get {
                return ResourceManager.GetString("Generic_ContactAdminError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Questions.
        /// </summary>
        internal static string HideQuestions {
            get {
                return ResourceManager.GetString("HideQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Connections.
        /// </summary>
        internal static string InternalConnection {
            get {
                return ResourceManager.GetString("InternalConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lifecycles Selected.
        /// </summary>
        internal static string LifecycleSelected {
            get {
                return ResourceManager.GetString("LifecycleSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Marketing list.
        /// </summary>
        internal static string MarketingListTitle {
            get {
                return ResourceManager.GetString("MarketingListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minutes.
        /// </summary>
        internal static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A matching DOM Definition Execution Order record does not exist for this DOM Definition Logic record..
        /// </summary>
        internal static string Missing_Valid_DOM_Definition_Execution_Order_for_DOM_Definition_Logic {
            get {
                return ResourceManager.GetString("Missing_Valid_DOM_Definition_Execution_Order_for_DOM_Definition_Logic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A matching DOM Definition Logic record does not exist for this DOM Definition Execution Order record..
        /// </summary>
        internal static string Missing_Valid_DOM_Definition_Logic_for_DOM_Definition_Execution_Order {
            get {
                return ResourceManager.GetString("Missing_Valid_DOM_Definition_Logic_for_DOM_Definition_Execution_Order", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NO DATA FOUND.
        /// </summary>
        internal static string NoDataMessage {
            get {
                return ResourceManager.GetString("NoDataMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OkButton {
            get {
                return ResourceManager.GetString("OkButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options:.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Call.
        /// </summary>
        internal static string PhonecallButton {
            get {
                return ResourceManager.GetString("PhonecallButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while trying to predict the Retention Probability..
        /// </summary>
        internal static string PredictRetention_Failure {
            get {
                return ResourceManager.GetString("PredictRetention_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retention Probability was successfully updated..
        /// </summary>
        internal static string PredictRetention_Success {
            get {
                return ResourceManager.GetString("PredictRetention_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PREVIEW.
        /// </summary>
        internal static string PreviewContainerText {
            get {
                return ResourceManager.GetString("PreviewContainerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set duration in increments of quarter hours (0.25).
        /// </summary>
        internal static string QuaterHoursError {
            get {
                return ResourceManager.GetString("QuaterHoursError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question:.
        /// </summary>
        internal static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a question.
        /// </summary>
        internal static string QuestionPlaceHolder {
            get {
                return ResourceManager.GetString("QuestionPlaceHolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QUESTIONS.
        /// </summary>
        internal static string QuestionsContainerText {
            get {
                return ResourceManager.GetString("QuestionsContainerText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question.
        /// </summary>
        internal static string QuestionTitle {
            get {
                return ResourceManager.GetString("QuestionTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Note - Workflow to send request has not been defined..
        /// </summary>
        internal static string Recommendation_Invite_Workflow_NotConfigured {
            get {
                return ResourceManager.GetString("Recommendation_Invite_Workflow_NotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to copy, field(s) on the form have been modified..
        /// </summary>
        internal static string RecordFieldDirtyMessage {
            get {
                return ResourceManager.GetString("RecordFieldDirtyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Ribbon_Loading {
            get {
                return ResourceManager.GetString("Ribbon_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schedule Appointment.
        /// </summary>
        internal static string ScheduleAppointment {
            get {
                return ResourceManager.GetString("ScheduleAppointment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select....
        /// </summary>
        internal static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Lifecycles.
        /// </summary>
        internal static string SelectLifecycles {
            get {
                return ResourceManager.GetString("SelectLifecycles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select a question type.
        /// </summary>
        internal static string SelectQuestionType {
            get {
                return ResourceManager.GetString("SelectQuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Course Sections selected. Please search for and select a Campus Survey Template..
        /// </summary>
        internal static string SelectStaffSurvey {
            get {
                return ResourceManager.GetString("SelectStaffSurvey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a Campus Survey Template.
        /// </summary>
        internal static string SelectStaffSurveyTemplate {
            get {
                return ResourceManager.GetString("SelectStaffSurveyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student(s) selected. Please search for and select a Success Plan Template..
        /// </summary>
        internal static string SelectSuccessPlan {
            get {
                return ResourceManager.GetString("SelectSuccessPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Questions.
        /// </summary>
        internal static string ShowQuestions {
            get {
                return ResourceManager.GetString("ShowQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Calendar.
        /// </summary>
        internal static string StaffCalendarTitle {
            get {
                return ResourceManager.GetString("StaffCalendarTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus Survey(s) has been assigned for the selected Staff Course(s).
        /// </summary>
        internal static string StaffSurveyAssign {
            get {
                return ResourceManager.GetString("StaffSurveyAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus Surveys are not assigned as : -Existing Campus Surveys with matching dates or with dates within the matching dates are already assigned. - The start date of the Campus Survey is prior to the current date..
        /// </summary>
        internal static string StaffSurveyNotAssign {
            get {
                return ResourceManager.GetString("StaffSurveyNotAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Campus Survey Template.
        /// </summary>
        internal static string StaffSurveyTemplate {
            get {
                return ResourceManager.GetString("StaffSurveyTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a copy of this Campus Survey Template record?.
        /// </summary>
        internal static string StaffSurveyTemplate_Copy_DialogMessage {
            get {
                return ResourceManager.GetString("StaffSurveyTemplate_Copy_DialogMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy Campus Survey Template.
        /// </summary>
        internal static string StaffSurveyTemplate_Copy_DialogTitle {
            get {
                return ResourceManager.GetString("StaffSurveyTemplate_Copy_DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying Campus Survey Template....
        /// </summary>
        internal static string StaffSurveyTemplate_Copy_Loading {
            get {
                return ResourceManager.GetString("StaffSurveyTemplate_Copy_Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        internal static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end date must occur after the start date.
        /// </summary>
        internal static string StartDateGreaterthanEndDateError {
            get {
                return ResourceManager.GetString("StartDateGreaterthanEndDateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The end time must occur after the start time.
        /// </summary>
        internal static string StartTimeGreaterthanEndTimeError {
            get {
                return ResourceManager.GetString("StartTimeGreaterthanEndTimeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student1.
        /// </summary>
        internal static string Student1 {
            get {
                return ResourceManager.GetString("Student1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student2.
        /// </summary>
        internal static string Student2 {
            get {
                return ResourceManager.GetString("Student2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StudentName\Questions.
        /// </summary>
        internal static string StudentQuestionHeader {
            get {
                return ResourceManager.GetString("StudentQuestionHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to submit?.
        /// </summary>
        internal static string SubmitConfirmation {
            get {
                return ResourceManager.GetString("SubmitConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success Plan Template.
        /// </summary>
        internal static string SuccessPlanTemplate {
            get {
                return ResourceManager.GetString("SuccessPlanTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot copy the Success Plan Template, the form is missing the Copy Success Plan Template field..
        /// </summary>
        internal static string SuccessPlanTemplate_Copy_FormMissingCopySuccessPlanFieldMessage {
            get {
                return ResourceManager.GetString("SuccessPlanTemplate_Copy_FormMissingCopySuccessPlanFieldMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details cannot be saved as an associated Test Type is not available for the selected test. Contact your administrator..
        /// </summary>
        internal static string TestType_TypeNotConfigured {
            get {
                return ResourceManager.GetString("TestType_TypeNotConfigured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with : {0}.
        /// </summary>
        internal static string Timeline_Chatwith {
            get {
                return ResourceManager.GetString("Timeline_Chatwith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        internal static string TimelineCheckAll {
            get {
                return ResourceManager.GetString("TimelineCheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To-Do.
        /// </summary>
        internal static string ToDoButton {
            get {
                return ResourceManager.GetString("ToDoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed start and / or end dates are identical to or exceed the date range of associated trips..
        /// </summary>
        internal static string TravelMgmt_TripActivityExceedsDateRangeOfAssociatedTrip {
            get {
                return ResourceManager.GetString("TravelMgmt_TripActivityExceedsDateRangeOfAssociatedTrip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start and/or end dates are not in the date range of the associated trip..
        /// </summary>
        internal static string TravelMgmt_TripActivityStart_EndDateOutOfTripStart_EndDate {
            get {
                return ResourceManager.GetString("TravelMgmt_TripActivityStart_EndDateOutOfTripStart_EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trip is already approved or rejected. To view its updated status, refresh the page..
        /// </summary>
        internal static string TravelMgmt_TripAlreadyApprovedOrRejected {
            get {
                return ResourceManager.GetString("TravelMgmt_TripAlreadyApprovedOrRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A trip with the same start and/or end date is already available..
        /// </summary>
        internal static string TravelMgmt_Tripwithsamestart_enddate {
            get {
                return ResourceManager.GetString("TravelMgmt_Tripwithsamestart_enddate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel the trip?.
        /// </summary>
        internal static string Trip_Cancel {
            get {
                return ResourceManager.GetString("Trip_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the trip?.
        /// </summary>
        internal static string Trip_Complete {
            get {
                return ResourceManager.GetString("Trip_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Trip is already marked as Completed or Canceled..
        /// </summary>
        internal static string Trip_Completed_Cancelled {
            get {
                return ResourceManager.GetString("Trip_Completed_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trip.
        /// </summary>
        internal static string Trip_DialogTitle {
            get {
                return ResourceManager.GetString("Trip_DialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot mark the Trip as Completed because its Trip Status is not Approved..
        /// </summary>
        internal static string Trip_Not_Approved {
            get {
                return ResourceManager.GetString("Trip_Not_Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Trip cannot be marked as Canceled as some Trip Activities are marked as Complete..
        /// </summary>
        internal static string TripActivity_Not_Cancelled {
            get {
                return ResourceManager.GetString("TripActivity_Not_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Trip cannot be marked as Complete as some Trip Activities are marked as Planned, Requested or Confirmed..
        /// </summary>
        internal static string TripActivity_Not_Completed {
            get {
                return ResourceManager.GetString("TripActivity_Not_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The start and end dates must be on or within the start and end dates of the associated trip..
        /// </summary>
        internal static string TripActivityDateValidation {
            get {
                return ResourceManager.GetString("TripActivityDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        internal static string Unavailable {
            get {
                return ResourceManager.GetString("Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Lookup View.
        /// </summary>
        internal static string UserLookupView {
            get {
                return ResourceManager.GetString("UserLookupView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom: Alt+Scroll.
        /// </summary>
        internal static string ZoomTimeLine {
            get {
                return ResourceManager.GetString("ZoomTimeLine", resourceCulture);
            }
        }
    }
}
